### ISSUE TITLE
Suggested content - aligning columns in dataview tables

### ISSUE THREAD

**Issue by claremacrae** [s-blu/obsidian_dataview_example_vault#34]
I regret that I don't currently have capacity to add a PR for this, but it is such value info that I wanted to log it here, in case anyone else could figure out where to add it...

I asked in [Discord](https://discord.com/channels/686053708261228577/1014259487445622855/1027839166291116052)

> In a dataview table, is it possible to right-justify an individual column? I've hunted high and low...

````text
```dataview
TABLE WITHOUT ID
    ArrivalDate.year as Year,
    file.link AS Note,
    Link,
    Address,
    Sleeps,
    ArrivalDate,   << want to right-justify values
    DepartureDate, << want to right-justify values
    InDiary
FROM "..."
SORT ArrivalDate
WHERE ArrivalDate
```
````

`@mnvwvnm` replied in [Discord](https://discord.com/channels/686053708261228577/1014259487445622855/1027857346019459153)

> you can use also this "direct" way

````
```text
TABLE WITHOUT ID
    ArrivalDate.year as Year,
    file.link AS Note,
    Link,
    Address,
    Sleeps,
    r1 + ArrivalDate + r2 AS ArrivalDate,
    r1 + DepartureDate + r2 AS DepartureDate, 
    InDiary
FROM "..."
FLATTEN "<span style='display:flex; justify-content: right;'>" AS r1
FLATTEN "</span>" AS r2
WHERE ArrivalDate
SORT ArrivalDate
```
````

It works brilliantly!

**Comment by s-blu** [comment]
I added the page and updated the description accordingly to your suggestion. Maybe you want to check again. https://github.com/s-blu/obsidian_dataview_example_vault/blob/master/20%20Dataview%20Queries/Style%20dataview%20table%20columns.md

or published: https://s-blu.github.io/obsidian_dataview_example_vault/20%20Dataview%20Queries/Style%20dataview%20table%20columns/

**Comment by claremacrae** [comment]
Awesome - thank you!
