### ISSUE TITLE
the caculation does not show up, please help

### ISSUE THREAD

**Issue by webrunneronSun** [s-blu/obsidian_dataview_example_vault#37]
hi s-blu,

here's the caculation do not show up. this is first i add image in github, not sure it can be seen or not.

![image](https://user-images.githubusercontent.com/119090113/204439119-40b8eb01-891b-45df-a1ed-3bb0873eb84c.png)

b/r

**Comment by s-blu** [comment]
Hello again,

thanks for the report. Would be great if you paste me the name of the files here, so I don't need to type them from a screenshot. :) 
Here, some new test data were added that broke the script. I added a new function to the script to deal with it.

**Comment by webrunneronSun** [comment]
Thanks again @s-blu 

u are great! so fast to have it fixed. next time i will put the name of the pages.

thanks again.

**Comment by webrunneronSun** [comment]
i learnt a lot, really, from the example vault. i know nothing about coding, so the examples helps a lot!
