### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by ScottKillen** [s-blu/obsidian_dataview_example_vault#38]
The dataview example for 'List non existing links' no longer displays links in the current version. It only displays the link text

The DQL version [here](https://s-blu.github.io/obsidian_dataview_example_vault/20%20Dataview%20Queries/List%20non%20existing,%20linked%20pages/#sort-the-results-by-count-of-references) behaves differently from the dataviewjs version after the latest release of DV

**Comment by s-blu** [comment]
Hello, 

thanks for the headsup! I fixed the example - wrapping `l.link` into `dv.fileLink(l.link)` did the trick.
