### ISSUE TITLE
will you please check the page show a sum row for numeric values and durations?

### ISSUE THREAD

**Issue by webrunneronSun** [s-blu/obsidian_dataview_example_vault#42]
![2023-03-09_011917](https://user-images.githubusercontent.com/119090113/223785144-728c592e-6ca0-4698-96bf-2615a251ae43.png)

this seems not work.

thanks

**Comment by mazlumtoprak** [comment]
Hey @webrunneronSun ,

I had the same issue when fiddling around with the snippets. I guess you're using the same snippet as in  [here](https://github.com/s-blu/obsidian_dataview_example_vault/blob/2c54d1a761de4db84ac0d8118fc380045c81e370/20%20Dataview%20Queries/Show%20an%20average%20row%20on%20tables%20for%20numeric%20values%20or%20durations.md?plain=1#LL46C38-L46C38)

I changed the line from:
`sums.push(dataType === "duration" ? luxon.Duration.fromMillis(avg) : avg);`

to:
`sums.push(dataType === "duration" ? Luxon.Duration.fromMillis(avg) : avg);`

Which seems to do it's job.

![image](https://user-images.githubusercontent.com/17855960/236951682-a0196737-322e-490e-a7f8-8463cb8fb964.png)

best regards

**Comment by webrunneronSun** [comment]
hi @mazlumtoprak 
thanks for your answer.  i did not find any difference in :
```
I changed the line from:
sums.push(dataType === "duration" ? luxon.Duration.fromMillis(avg) : avg);

to:
sums.push(dataType === "duration" ? Luxon.Duration.fromMillis(avg) : avg);
```
could you make it more details?

thanks

BR

**Comment by webrunneronSun** [comment]
read it again, 

did you meant change the `avg` to `sum`?

**Comment by FeralFlora** [comment]
> read it again,
> 
> did you meant change the `avg` to `sum`?

No, just make `Luxon` capitalized 👍 Thanks for making this issue, btw, I had the same problem and found the solution here immediately due to this issue (only one open).

**Comment by s-blu** [comment]
Hello! Thanks for reporting. Sorry it took me a while to come back to this!

I changed the query to use `dv.luxon` instead of luxon. I think `luxon` is the obsidian internal function and deemed it safer to use the one exposed over dataview. Should work all the same though :)
