### ISSUE TITLE
When sleeping the next day..

### ISSUE THREAD

**Issue by jun6lee** [s-blu/obsidian_dataview_example_vault#43]
Stumbled into this vault via Reddit and super glad I did, have learned a lot from this useful vault in the last week.
Am racking my brains on what I want is actually viable or if I'll need to change the way I store my data.

TABLE WITHOUT ID Wake as Wake, Sleep as Sleep, Awake, Slept 
FROM "Calendar/Daily Notes" 
FLATTEN dateformat(file.day, "yyyy-MM-dd") as dt
FLATTEN (date(dt + "T" + Sleep) + dur("1d")) - date(dt + "T" + Wake) as Awake
FLATTEN dur("24hrs") - Awake as Slept
SORT file DESC
LIMIT 1

This does the trick if I'm storing my Wake and Sleep times in a daily note respectively -- but I'm not.
So what I actually want to do is calculate my sleep on the basis of a SLEEP in Yesterday's Note and a WAKE in Today's Note.

I view my daily note through the day and fill tasks and bullets as they happen, sleep is the last thing I journal and is usually past 12.
With doing the above I get quite an ugly section until the end of the day when I put in a value.

Would appreciate any thoughts.

**Comment by s-blu** [comment]
Hello!

You might be better off asking these questions either in the dataview channel of the Obsidian Discord or in the [Discussion Section of the official dataview repository](https://github.com/blacksmithgu/obsidian-dataview/discussions) :) That said, I'm happy to try to help you. 

If I get you right, you want to take the "sleep" meta field of yesterdays note for the calculations, not todays? You should be able to do this by link indexing: https://blacksmithgu.github.io/obsidian-dataview/reference/expressions/#links

If your daily file notes are named like `yyyy-MM-dd`, this could work: 

```dataview
TABLE Wake as Wake, ySleep as Sleep, Awake, Slept  
FROM "test"  
FLATTEN dateformat(file.day, "yyyy-MM-dd") as dt 
FLATTEN dateformat(file.day - dur("1d"), "yyyy-MM-dd") as yesterday
FLATTEN link(yesterday).Sleep as ySleep
FLATTEN (date(yesterday + "T" + ySleep)) - date(dt + "T" + Wake) as Awake  
FLATTEN dur("24hrs") - Awake as Slept  
SORT file DESC 
LIMIT 1
```
It calculates the date of yesterday by substracting one day of the date (date/duration calculations are really handy) and then uses yesterday's date and yesterdays sleep time for the calculation.

This does not solve your problem if your sleep time is past midnight. We can do a small trick with the choice() function here. If we assume that you go to bed before 10:00 AM, we can check if your sleep time is bigger than 10:00 - if its something like 23:30, its is, if it is something like 01:23, it's not, so we can assume that when your sleep time is smaller than 10:00, you went to bed after midnight and use either yesterdays or todays date for the calculation based on that: 

```dataview
TABLE Wake as Wake, ySleep as Sleep, Awake, Slept  
FROM "test"  
FLATTEN dateformat(file.day, "yyyy-MM-dd") as dt 
FLATTEN dateformat(file.day - dur("1d"), "yyyy-MM-dd") as yesterday
FLATTEN link(yesterday).Sleep as ySleep
FLATTEN date(dt + "T" + Wake) - date(choice(ySleep > "10:00", yesterday, dt) + "T" + ySleep) as Slept  
FLATTEN dur("24hrs") - Slept as Awake
SORT file DESC 
LIMIT 1
```

For whatever reason, I needed to switch the Slept and Awake calculation and order to get back results for both durations. I didn't really got that, if I'm honest.

Hope that helps you!

**Comment by jun6lee** [comment]
You're right, going forward, will do that for such help -- useful to the community too.

Two Leanings for me here:
- The use of link(yesterday) was one nugget of information I was missing.
- The logic that was breaking my calculation if sleep is before or after midnight needed this: date(choice(ySleep > "10:00", yesterday, dt)


Thank you very much, this worked a treat, now I can adventure on to see how the tracker plugin works..  :)
